cwsFolderGallery:
   # defines pixel size of cropped album cover and album image thumbnails
   # Note: adapt "css/cwsoft-foldergallery.css" if you change the dimensions below
   THUMBNAIL_IMAGE_WIDTH: 150		
   THUMBNAIL_IMAGE_HEIGHT: 115
  
   # defines max. pixel dimension of resized jQuery preview image (original image ratio kept)
   PREVIEW_IMAGE_MAX_SIZE: 800
   
   # defines number of albums and images displayed per page (pagination limit)
   ALBUMS_PER_PAGE: 16
   IMAGES_PER_PAGE: 12
   
   # defines sort option by which images are displayed (1:Filename, 2:CreationTime, 3:LastEdited)
   IMAGE_SORT_OPTION: 1
   
   # defines sort order by which images are displayed (1:Ascending, 2:Descending)
   IMAGE_SORT_ORDER: 1
   
   # flag to display breadcrumbs at top of album pages (only if at least one parent page exists)
   SHOW_BREADCRUMBS: true